from enum import Enum


class DaqType(Enum):
    NIDAQMX = 1
    MOCK_SENSOR = 9
    UNDEFINED = 0


DAQ_TYPE = DaqType.UNDEFINED

SETTINGS_FILE_EXTENSION = ".toml"
DEFAULT_SETTINGS_FILE = "pyForceDAQ.settings" + SETTINGS_FILE_EXTENSION
DEFAULT_OUTPUT_FILENAME = None
